spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone=UTC
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

